apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  labels:
    app: pyapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
<<<<<<< HEAD
          image: kuragayalaakhil/gha-pyapp:9f28db4
=======
          image: kuragayalaakhil/gha-pyapp:987af9f
>>>>>>> bcadd17 (wip)
          ports:
            - containerPort: 8000
